In [4]:
# coding: utf-8
import numpy as np

# 1D array
A = np.array([1, 2, 3, 4])
print(A)
print(np.ndim(A))
print(A.shape)

B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)
print(np.ndim(B))
print(B.shape)
print("\n")

# 2D array (2x2) * (2x2)
A = np.array([[1, 2], [3, 4]])
print(A.shape)

B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
print("\n")

# 2D array (2x3) * (3x2)
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.shape)
print(A)

B = np.array([[1, 2], [3, 4], [5, 6]])
print(B.shape)
print(B)

np.dot(A, B)
print("\n")

# 2D array (1x2) * (2x3)
X = np.array([1, 2])
print(X)

W = np.array([[1,3,5], [2,4,6]])
print(W)

Y = np.dot(X, W)
print(Y)

[1 2 3 4]
1
(4,)
[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


(2, 2)


(2, 3)
[[1 2 3]
 [4 5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]


[1 2]
[[1 3 5]
 [2 4 6]]
[ 5 11 17]
