In [2]:
import pandas as pd
import numpy as np

import os

def load_hotel_reserve():
  customer_tb = pd.read_csv('../awesomebook-master/data/customer.csv')
  hotel_tb = pd.read_csv('../awesomebook-master/data/hotel.csv')
  reserve_tb = pd.read_csv('../awesomebook-master/data/reserve.csv')
  return customer_tb, hotel_tb, reserve_tb


def load_holiday_mst():
  holiday_tb = pd.read_csv('../awesomebook-master/data/holiday_mst.csv',
                           index_col=False)
  return holiday_tb


def load_production():
  production_tb = pd.read_csv('../awesomebook-master/data/production.csv')
  return production_tb


def load_production_missing_num():
  production_tb = pd.read_csv('../awesomebook-master/data/production_missing_num.csv')
  return production_tb


def load_production_missing_category():
  production_tb = pd.read_csv('../awesomebook-master/data/production_missing_category.csv')
  return production_tb


def load_monthly_index():
  monthly_index_tb = \
    pd.read_csv('../awesomebook-master/data/monthly_index.csv')
  return monthly_index_tb


def load_meros_txt():
  with open('../awesomebook-master/data/txt/meros.txt', 'r') as f:
    meros = f.read()
    f.close()
  return meros


In [3]:
customer_tb, hotel_tb, reserve_tb = load_hotel_reserve()

In [4]:
pd.pivot_table(reserve_tb, 
               index='customer_id', 
               columns='people_num',
               values='reserve_id',
               aggfunc=lambda x: len(x),
               fill_value=0)

people_num   1  2  3  4
customer_id            
c_1          2  2  2  2
c_10         0  2  2  2
c_100        2  1  2  0
c_1000       1  0  0  1
c_101        2  1  1  1
...         .. .. .. ..
c_994        1  0  0  0
c_995        2  2  1  3
c_996        0  4  3  0
c_997        0  1  1  0
c_999        1  3  1  1

[888 rows x 4 columns]

In [5]:
from scipy.sparse import csc_matrix

cnt_tb = reserve_tb.groupby(['customer_id', 'people_num'])['reserve_id'] \
                   .size() \
                   .reset_index()
cnt_tb.columns = ['customer_id', 'people_num', 'rsv_cnt']

customer_id = pd.Categorical(cnt_tb['customer_id'])
people_num = pd.Categorical(cnt_tb['people_num'])

sparse_matrix = csc_matrix((cnt_tb['rsv_cnt'], (customer_id.codes, people_num.codes)),
                            shape=(len(customer_id.categories), len(people_num.categories)))

print(sparse_matrix.toarray())

[[2 2 2 2]
 [0 2 2 2]
 [2 1 2 0]
 ...
 [0 4 3 0]
 [0 1 1 0]
 [1 3 1 1]]
